# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2e3a84f3e0fa88bc4b1076d0ad0418c268bd2cd5acec8ee7aac9b2a4704588274bb4d8efcbf171ff59a34cce2ebff5798b4b20d07034134bf0f50de4a150f4c

test:
  secret_key_base: 3fc944e665da64e5ad99f6af3a446c786565b149e2cf39e15e9f01d429ae2ee9aacca9b373b2bbf671eccecad6aed78feba16a8826d4c419544f5a6c66af6801

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
